### ISSUE TITLE
Move data to SPI flash

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#101]
Things are getting tight. It might be worth putting lookup tables and such onto an external EEPROM. That may allow us to support more than only K-type thermocouples.

Ideas
- Move K-type table to EEPROM
- Add support for other thermocouple types to EEPROM
- Add fonts to EEPROM
- Move text strings to EEPROM
- Even if this is not necessary for the T400, if a significant amount of flash on the ATmeag32U4 can be freed up, it may be worth doing to support hackers.

Questions
- How much space would be gotten via this method?
- How much space is required to support reading/writing EEPROM?
- How much would this cost?
- Is it fast enough?
- How much would this affect the power consumption?

**Comment by cibomahto** [comment]
Here are the largest code sections in the memory: 

avr-readelf /var/folders/4x/1098rs3s6n3g6vqgl89p5msr0000gn/T/build2511438885760059927.tmp/t400.cpp.elf -s |perl -ne 'if(/(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)/) { print $3 . " " . $8. "\n";}'|sort -n -r
1004 loop
982 _Z4drawR14U8GLIB_PI13264P
932 vfprintf
805 u8g_font_5x8r
764 dtoa_prf
602 __vector_36
576 _ZN5Fat165writeEPKvj
560 __vector_11
512 _ZN5Fat1612cacheBuffer_E
510 _ZN5Fat164initEP6SdCardh
446 _ZN5Fat164openEPKch
434 _Z11GetTypKTempd
432 __ftoa_engine
404 _ZL8tempTypK
400 graph
344 u8g_dev_rot180_fn
340 u8g_GetGlyph
294 _ZN2sd4initEPc
290 _ZN5Fat167seekSetEm
286 _Z8USB_SendhPKvi
280 u8g_dev_st7567_pi13264_fn
280 _ZN5Fat168truncateEm
278 _Z11updateGraphPd
270 setup
244 u8g_com_arduino_hw_spi_fn
240 _Z10DS3231_getP2ts
226 _ZN5Fat164openEjh
218 _ZN6SdCard5beginEhh
216 u8g_draw_glyph
204 u8g_WriteEscSeqP
204 __divsf3x
204 _ZN5Fat166fatPutEjj
194 __mulsf3x
192 __addsf3x
188 __ultoa_invert
188 _ZN5Fat1610addClusterEv
184 _ZN7Buttons10buttonTaskEv
178 u8g_DrawLine
178 _ZN5Print11printNumberEmh
172 init
172 _ZN7MCP342416measurementR
172 _ZN6SdCard11cardCommandEh
170 _Z9CDC_SetupR5Setup
166 twi_writeTo
162 _ZN6SdCard10writeBlockEmP
156 __vector_10
148 __vector_23
146 u8g_dev_pb8v1_base_fn
144 u8g_UpdateRefHeight
138 _ZN5Fat166fatGetEjPj
138 _Z8USB_RecvhPvi
136 twi_readFrom
132 u8g_dev_st7567_pi13264_hw
128 _ZN5Fat1610cacheFlushEv
126 u8g_pb8v1_Set8PixelOpt2
124 _ZN5Fat164syncEv
122 turnOffPWM
122 __floatunsisf
114 pinMode
114 _ZN5Fat1613cacheRawBlockE
110 u8g_DrawStr
108 digitalWrite
108 _ZN7MCP980X11readTempC16E
108 _ZL24USB_SendStringDescri
104 _ZN6SdCard12readTransferE
104 _ZN2sd4syncEb
100 u8g_InitLL
100 fputc


The font is 805 bytes and the temperature table is 404 bytes, and there are some more U8G sections that I missed earlier.

**Comment by cibomahto** [comment]
From an implementation standpoint, it would be easiest to move the temperature table to eeprom (or flash of course)

**Comment by charlespax** [comment]
Cool. The T400 is advertised to support k-type thermocouples. If someone wants another type, they can hack in a different lookup table. Reading a table from the SD card is something that maybe some hacks into the firmware in the future. We don't need this now.

We have 1k of EEPROM, so we would have to choose between storing the font in EEPROM or the lookup table. If we implement the large readings on the LCD (https://github.com/PaxInstruments/t400-firmware/issues/117), we would need the SPI flash to store the font. Do I have this right?

I've already committed to shipping with the SPI flash chip. Saving the cost of the SPI flash chip is a nice-to-have item if we can avoid it without compromising the device. For example, I would rather have the large number feature (https://github.com/PaxInstruments/t400-firmware/issues/117) and use the SPI flash than to save the cost and sacrifice the feature.

@cibomahto Basically, the SPI flash is there for you to use as you see fit.

**Comment by cibomahto** [comment]
Basically correct. It's easier to put the temperature lookup table there since it avoids touching the library.

The sketch is currently at ~25k, so there are ~3600 bytes free before offloading anything. It'll probably take at least 1000 more bytes to implement the remaining features, but we're not under too much pressure at the moment.

**Comment by charlespax** [comment]
I'm going to ship the T400 with the SPI flash chip. It will be there in the future if we want to use it. It sounds like we won't be using it on the shipping firmware, so we can probably move this to the ice box.

**Comment by charlespax** [comment]
Will not implement unless this come up as a memory wall. Then we can file a new bug and pick up the discussion. Closing issue.

**Comment by davidbuzz** [comment]
just a quick note on this issue for a related thing:    it's pretty easy now to disable the SDCard logging functionality to free up a bunch of space which although it reduces shipped functionality, it might suit some people.  see https://github.com/PaxInstruments/t400-firmware/pull/198
