### ISSUE TITLE
Buttons test PASSes PWR button

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#123]
In the t400-testing program the button test works for all the buttons except for the power button. It looks like the BUTTON_POWER_PIN is always at 3.2 volts.

**Comment by samchoy88** [comment]
Oh, this is related to the issue I report before.
SW_PWR cannot detect button action #116

Please change the r6 resistor value become 2k

**Comment by charlespax** [comment]
The firmware for t400-testing version 0.1 makes an exception for this bug. We should fix it in the next version (https://github.com/PaxInstruments/t400-firmware/issues/135).
