### ISSUE TITLE
60s log interval too fast

### ISSUE THREAD

**Issue by cibomahto** [PaxInstruments/t400-firmware#145]
30s seems to be fine, but 60s is very fast. Possibly a rollover problem?

**Comment by charlespax** [comment]
This is happening with the RTC_INT triggering the readings?

**Comment by cibomahto** [comment]
This is with atmega-based timing, not the RTC_INT yet. It'll likely be irrelevant once the RTC triggers the system.

**Comment by charlespax** [comment]
We should either move this issue to a future milestone or pull the dependencies into this milestone. @cibomahto what do you recommend?

Dependencies:

- RTC: Set RTC date/time (https://github.com/PaxInstruments/t400-firmware/issues/51)
- RTC: Set interrupt alarms (https://github.com/PaxInstruments/t400-firmware/issues/50)
- RTC: RTC interrupt mask triggers readings (https://github.com/PaxInstruments/t400-firmware/issues/53)

**Comment by cibomahto** [comment]
In that case, just drop it- the code with this bug will be rewritten to support RTC timing.
