### ISSUE TITLE
Arduino IDE 1.6

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#146]
Arduino just released version 1.6 or their IDE. Should we use the new version as our standard for development?

In the release notes there didn't seem to be anything that would affect us significantly. However, this release includes a "Fix for upload problems on Leonardo, Micro and Yún." I'm not sure what those problems are though.

**Comment by cibomahto** [comment]
Yep, good idea. It's a complete change in compiler, and a healthy change in system libraries- probably better to jump to the new one now.

**Comment by cibomahto** [comment]
Seems fine. Use 1.6 from now on ;-)
