### ISSUE TITLE
Graph indicator alignment

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#147]
In commit 6b4233eadb422f27645603a8306646cb7c448231 the numbers to the right of the graph to match up with the graph lines.
![img_20150215_220703](https://cloud.githubusercontent.com/assets/281642/6207477/6c317762-b5dd-11e4-948a-c8bbc422d985.jpg)

They appear to be inverted. In the images below you can see the temperature on sensor 1 decreasing while the label "1" moves up.
![img_20150215_221055](https://cloud.githubusercontent.com/assets/281642/6207487/b26a3da4-b5dd-11e4-8d69-6f1de3b369e0.jpg)
![img_20150215_221108](https://cloud.githubusercontent.com/assets/281642/6207488/b43adf6c-b5dd-11e4-8771-9d2492f991d8.jpg)
![img_20150215_221111](https://cloud.githubusercontent.com/assets/281642/6207489/b6a429ac-b5dd-11e4-9063-eb72376d4dde.jpg)
![img_20150215_221203](https://cloud.githubusercontent.com/assets/281642/6207490/b7b5b324-b5dd-11e4-83be-5b2d4691b8e3.jpg)

**Comment by charlespax** [comment]
Adding to GRAPHING

**Comment by charlespax** [comment]
Actually, I'm moving it to Firmware version 0.2 because it aligns with the milestone theme of graphing. Also it will need to be fixed to meet the milestone description of, "At the end of this milestone the graphing system should be functional and display correctly."

**Comment by cibomahto** [comment]
Fixed in fed283e
