### ISSUE TITLE
LCD update rate

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#150]
What can be done to speed up the refresh rate of the LCD? What factors limit the refresh rate?

- We may be able to buffer larger portions of the screen, but that would eat up more MCU RAM (see https://github.com/PaxInstruments/t400-firmware/issues/81)
- Maybe we can speed up the SPI communication
- Maybe it would be help

**Comment by cibomahto** [comment]
The correct term here is 'update rate'. The refresh rate is handled by the controller built into the LCD.

The buffer size won't have much of an effect, that's mostly been optimized- see draw() in functions.cpp.

It might be possible to optimize the SPI communication to increase output speed.

**Comment by charlespax** [comment]
Here is a relevant post about optimizing the update rate. http://jeelabs.org/2010/11/19/speedier-graphics/

**Comment by cibomahto** [comment]
I don't think this is a limiting factor in the system performance.

**Comment by charlespax** [comment]
I agree. I was just dumping some ideas. Moving this to the ice box (Formerly "Firmware version :-)").

**Comment by charlespax** [comment]
What are the limiting factors?

**Comment by charlespax** [comment]
From our conversation I understand that the biggest limiting factor is the processor preparing the buffer to write to the screen. A faster processor with enough ram to buffer the entire screen should be able to update quickly.

This will be important int he future when we move to a better chip. Using the same LCD shouldn't be a problem.
