### ISSUE TITLE
Points are graphed while no thermocouples present

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#151]
With the firmware in commit 6b4233eadb422f27645603a8306646cb7c448231 there are points on the graph when there are no thermocouples present.

![img_20150219_165211](https://cloud.githubusercontent.com/assets/281642/6263834/1d77d440-b858-11e4-914f-a2e1d7af0d6f.jpg)

**Comment by cibomahto** [comment]
Typo. fixed in 4659997a0b26
