### ISSUE TITLE
Power button

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#152]
1) When the device is off and the power button is pressed, the device should turn on. This is implemented. The hardware gives power to the device and the software keeps the power on.

2) When the device is on and the power button is pressed for some time interval, the device should turn off.

3) the functionality of 2 should not interfere with the functionality of 1;  after turning on the device the user must release the power button before the device can be turned off.

**Comment by charlespax** [comment]
I'm moving this to UX.

**Comment by cibomahto** [comment]
Turns out that the hardware pin is connected to the SS pin (PB0) on Rev12, so the power button can't actually be used. I recommend swapping this with the power on/off output (PB7), as the SS pin can still be used as a GPIO output.

**Comment by charlespax** [comment]
For info on the interrupt pins see https://github.com/PaxInstruments/t400-electronics/issues/143

**Comment by cibomahto** [comment]
Actually it is best to avoid SS as it gets toggled during SPI init (which then shuts off the board). This works:
Move SW_POWER to PB7 (D11)
Move POWER_ONOFF to PD5 (TXLED/D30)

**Comment by cibomahto** [comment]
Implemented in 690b2f6. Requires an update to the bootloader and board definition file as well:
https://github.com/PaxInstruments/ATmega32U4-bootloader/commit/c14d7102692cd88ac141dae1a0a6f0d3ee7ebdd7

Filed an issue in the electronics repo here:
https://github.com/PaxInstruments/t400-electronics/issues/184
