### ISSUE TITLE
Add CSV header to serial output on logging start

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#154]
When we make a new CSV file we add a header to it. Maybe the serial output should give the same header when the a new file is created

This is what it could look like.
```
00:03:07, 22.75, 22.95, -, -, 25.31
00:03:08, 22.75, 23.14, -, -, 25.51
00:03:09, 22.75, 23.14, -, -, 25.51
Logging to:
LD0029.CSV
time, ambient, sens0, sens1, sens2, sens3
00:00:00, 22.69, 23.08, -, -, 25.25
00:00:01, 22.75, 23.14, -, -, 25.31
00:00:02, 22.81, 23.40, -, -, 25.37
00:00:03, 22.75, 23.14, -, -, 25.31
00:00:04, 22.75, 23.34, -, -, 25.31
```

**Comment by cibomahto** [comment]
Implemented in 3cf53a7f3c - the same header information is now written to both SD and serial. Displaying time since start instead of the system time is a separate issue.
