### ISSUE TITLE
Y-axis tick marks

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#155]
In testing commit a1822c39e5e20fde18b2a8dd2b465f2e9ac9cf90 I found that the Y-axis tick marks are missing.

How things are now:
![img_20150220_234520](https://cloud.githubusercontent.com/assets/281642/6289438/370b1a58-b95b-11e4-8d9b-c3ff3a7f1055.jpg)

How things used to be:
![screen shot 2015-02-20 at 23 44 57](https://cloud.githubusercontent.com/assets/281642/6289437/3589fb04-b95b-11e4-93bc-1d131d58a599.png)

**Comment by cibomahto** [comment]
Good catch.

**Comment by cibomahto** [comment]
Fixed in 2d60526
