### ISSUE TITLE
Temperature data persistence

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#156]
In commit ee0c6c6, as the user switches between units (K, C, F), the data gets wiped from the graph. It would be nice if the data persisted while changing units. I imagine this would have some calculation overhead.

Not essential to the minimum viable product. Moving to ice box.

**Comment by cibomahto** [comment]
Yeah, that would be nicer. This is actually waiting on automatic graph scaling- once that works, the conversion setup will be similar (all data should be scaled & shifted based on the difference between the previous scale and the new one). The graph doesn't actually know about units. There's an issue open for the automatic scaling already.

**Comment by charlespax** [comment]
Should I mark this as a bug and toss it in GRAPHING?

**Comment by cibomahto** [comment]
If you want to, sure. I have it marked as a TODO in the code

**Comment by charlespax** [comment]
Not necessary to ship, so I'm moving to ice box.

**Comment by charlespax** [comment]
It is fine for changing time base to blast the data.

**Comment by protological** [comment]
Since the actual temperature values are in the array, it should be pretty easy to do the 'convert' function at display time rather than sample time.  Doing this and removing the reset function call when the button is pressed should allow for  'persistent' data.

This was added to the performance_changes branch

**Comment by protological** [comment]
Added in commit d736e22a864211ac280730f84d28d12f07f64866
