### ISSUE TITLE
Arduino boot delay

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#165]
It would be cool if the normal Arduino boot delay is skipped, so we can boot faster. Maybe have the bootloader check for a specific key press combination. If the keys are not pressed, move directly to firmware. If keys are pressed, proceed with the normal delay. This would result in the user needing to hold down keys while flashing new firmware.

**Comment by charlespax** [comment]
Maybe this should go in the bootloader repo issues.

**Comment by cibomahto** [comment]
The button thing is already implemented, and Caterina does not have a boot delay on regular startup.
![screen shot 2015-06-05 at 9 22 20 pm](https://cloud.githubusercontent.com/assets/44493/8006737/02c798f0-0bc9-11e5-89a1-c99f065b233c.png)
