### ISSUE TITLE
Need icon for no battery state

### ISSUE THREAD

**Issue by cibomahto** [PaxInstruments/t400-firmware#173]
I put in a placeholder, if it's fine then close this issue
No battery: ![no_batt](https://cloud.githubusercontent.com/assets/44493/9287643/08f73f26-4352-11e5-8c03-5e6e87de5881.png)

**Comment by charlespax** [comment]
I think the E if good. I've mocked up some other options, but I don't think any of them both look good and make it clear there is an error. Closing issue.

![screen shot 2015-08-15 at 13 51 53](https://cloud.githubusercontent.com/assets/281642/9287691/e0271168-4354-11e5-8849-d6523f5049ef.png) ![screen shot 2015-08-15 at 13 52 18](https://cloud.githubusercontent.com/assets/281642/9287692/e02da834-4354-11e5-864a-e38a2f43e683.png) ![screen shot 2015-08-15 at 13 49 41](https://cloud.githubusercontent.com/assets/281642/9287693/e034bc3c-4354-11e5-9651-f8cacfe1d6b8.png) ![screen shot 2015-08-15 at 13 46 59](https://cloud.githubusercontent.com/assets/281642/9287677/26568f16-4354-11e5-924a-be2495811a3b.png) ![screen shot 2015-08-15 at 13 42 26](https://cloud.githubusercontent.com/assets/281642/9287678/265d73e4-4354-11e5-937c-a97752cb9a59.png) ![screen shot 2015-08-15 at 13 43 35](https://cloud.githubusercontent.com/assets/281642/9287679/26aa38dc-4354-11e5-863e-4ed5a2644157.png) ![screen shot 2015-08-15 at 13 42 59](https://cloud.githubusercontent.com/assets/281642/9287680/26b44f34-4354-11e5-8406-fcf541db6869.png) ![screen shot 2015-08-15 at 13 46 34](https://cloud.githubusercontent.com/assets/281642/9287681/26dd17c0-4354-11e5-94e2-e154506b1b2a.png) ![screen shot 2015-08-15 at 13 42 40](https://cloud.githubusercontent.com/assets/281642/9287682/26e7bbd0-4354-11e5-9573-75d5dd2b2d98.png) ![screen shot 2015-08-15 at 13 43 08](https://cloud.githubusercontent.com/assets/281642/9287683/26eee392-4354-11e5-8766-ce90187f4f1c.png) ![screen shot 2015-08-15 at 13 42 50](https://cloud.githubusercontent.com/assets/281642/9287684/26f3d4ec-4354-11e5-978d-bc5851db2b30.png)
