### ISSUE TITLE
Changing SD card

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#174]
I'm running the old firmware for MakerFaire Shenzhen, so I don't know if this would still be an issue. It looks like a user must power cycle the device after swapping SD cards. Otherwise, it can appear as if the device is recording. This is realated to throwing SD errors (https://github.com/PaxInstruments/t400-firmware/issues/34).

- Put MicroSD in device, turn on
- Start and stop logging several times to confirm the device is writing new files to the SD card. Make note of the las file name, for example LD0005.csv
- Stop logging
- Remove the SD card and replace with another one
- Start and stop logging several times and you will see that the file name is always LD0005.csv and no file is saved to SD
- Power cycle the device
- Start and stop logging and each time you will see a new file name and a new file on the SD card.

A solution may be to reinitialize the SD card every time logging starts.

**Comment by cibomahto** [comment]
Addressed in 3cf53a7. The SD card is now re-initialized before opening a new log file, and a file open error or any write errors cause the logging to be stopped.
