### ISSUE TITLE
When battery voltage too low, display wraps to full again

### ISSUE THREAD

**Issue by cibomahto** [PaxInstruments/t400-firmware#177]
Need to clamp the battery measurement function both high and low.

Note: Battery measurement testing can be sped up by adding a power resistor across the 3.3V line, otherwise it actually will take days.

**Comment by charlespax** [comment]
Is this because the ADC is giving a negative value?

**Comment by protological** [comment]
The delta operation could be a negative number,  checking before should fix the problem.  Added in commit 239010f9970320926f5a5e62eaf2df624e6907b9
