### ISSUE TITLE
When interval >1s, switching intervals or temperature units gives 1 frame of ugly graph

### ISSUE THREAD

**Issue by cibomahto** [PaxInstruments/t400-firmware#179]
There is a workaround for this, but it seems broken for >1s delays.

**Comment by charlespax** [comment]
I'm not seeing this in the latest firmware. However, the graph does appear to stay ugly rather than for just one frame. I mention this in https://github.com/PaxInstruments/t400-firmware/issues/178.

I think we can close this unless you are still experiencing this issue.

**Comment by charlespax** [comment]
This does not seem to happen how that I changed the temperature range in graphReset(). See #178
