### ISSUE TITLE
Disabled button feedback

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#193]
Several buttons are disabled while logging. If a user presses one, there should be feedback indicating that the press was registered, but that function will not work. The user should not get the impression that the device is malfunctioning.

Maybe flash the file name. Maybe flash LOGGING and then the file name again.

**Comment by protological** [comment]
Added logic to show "Disabled while logging" on the status bar page for 2 seconds based on a flag.

Added in commit 3130d664bf697cdc51fe9a68b836d3d5f1280028
