### ISSUE TITLE
File locations and quantities

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#195]
Maybe save to directories when using a FAT12 filesystem. I think there is a 128 or 512 limit to how many files can be in the root directory while subdirectories can be more.

Also consider giving feedback to the user if the file quantity is reached. However, it would be better to quietly make a new directory.

**Comment by protological** [comment]
The mkdir function in sdFat takes up about 1k of flash space.  I don't think we should add this large chunk to the t400.  The limit for the root directory appears to be 512 entries based on testing an SD card.  We can show a message in the status bar when we we can't up a file.

**Comment by protological** [comment]
Message added in commit 699a5eed6eff56ccfec0f20ce65962f0aa16644f
