### ISSUE TITLE
Detect LiPo charge state

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#20]
Detect LiPo STAT (HIGH == full, LOW == other). The charge state can be indicated on the LCD. When plugged in blinking battery means charging, a solid battery means full.

**Comment by charlespax** [comment]
We may need to change the part. See https://github.com/PaxInstruments/t400-electronics/issues/159

**Comment by cibomahto** [comment]
Covered in issue https://github.com/PaxInstruments/t400-firmware/issues/18, the cell phone battery used now doesn't have a separate stat output.
