### ISSUE TITLE
Use ATmega32U4 internal voltage reference

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#21]
Use the ATmega32U4 internal 2.5 V reference voltage when taking an analog reading. This is useful for measuring the battery voltage as the battery drains and the system voltage runs down. Calibrate this at the factory. http://provideyourown.com/2012/secret-arduino-voltmeter-measure-battery-voltage/

**Comment by charlespax** [comment]
This has been implemented in Electronics version 0.10 (https://github.com/PaxInstruments/t400-electronics/issues/43).

**Comment by cibomahto** [comment]
Closing this, and adding note to #18 to cover it.
