### ISSUE TITLE
Double negative

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#222]
Here is a weird one.
![img_20160713_111627](https://cloud.githubusercontent.com/assets/281642/16790846/ba4614e2-48eb-11e6-8a34-f3387c07dd77.jpg)

**Comment by protological** [comment]
This is based on how we show the new 1/10th temperature values.  The fraction = int16%10 which will result in a negative fraction if the value is negative.  Adding abs() should solve this.  This will be in a bug fix branch with the wonky numbers

**Comment by protological** [comment]
Fixed in commit 62c3869c697e2f53c39fbb5296fdc5a7a2bc6a43
