### ISSUE TITLE
If held down starting at boot, releasing the power button causes the device to turn off again

### ISSUE THREAD

**Issue by cibomahto** [PaxInstruments/t400-firmware#3]
Obviously this isn't desireable

**Comment by charlespax** [comment]
We should fix this early, but I'm moving it now to Firmware version 0.x UX or classification.

**Comment by cibomahto** [comment]
Closing this since the relevant hardware has gone though multiple revisions since it was reported. Will re-evaluate after V.11

**Comment by charlespax** [comment]
I listed the power button functionality in issue#152.
