### ISSUE TITLE
SD: Throw errors for missing SD card or other faults

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#34]

**Comment by charlespax** [comment]
In the version I'm running on a prototype when the logging start/stop button is pressed and there is no SD card present the display will show that we are logging to LD0000.CSV. This is a case that should throw some sort of error or minimally, not do anything.

**Comment by cibomahto** [comment]
Addressed in 3cf53a7. The SD card is now re-initialized before opening a new log file, and a file open error or any write errors cause the logging to be stopped.
