### ISSUE TITLE
Serial: Print time since logging began to serial port

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#38]

**Comment by cibomahto** [comment]
Please update the issue with a description of how to implement this, or close it.

**Comment by charlespax** [comment]
In commit a1822c39e5e20fde18b2a8dd2b465f2e9ac9cf90 we have the following output for the serial terminal and the CSV.

Output of the serial terminal:
```
00:03:07, 22.75, 22.95, -, -, 25.31
00:03:08, 22.75, 23.14, -, -, 25.51
00:03:09, 22.75, 23.14, -, -, 25.51
Logging to:
LD0029.CSV
00:03:11, 22.69, 23.08, -, -, 25.25
00:03:12, 22.75, 23.14, -, -, 25.31
00:03:13, 22.81, 23.40, -, -, 25.37
00:03:14, 22.75, 23.14, -, -, 25.31
00:03:15, 22.75, 23.34, -, -, 25.31
```

Output of the CSV file:
```
time, ambient, sens0, sens1, sens2, sens3
00:03:11, 22.69, 23.08, -, -, 25.25
00:03:12, 22.75, 23.14, -, -, 25.31
00:03:13, 22.81, 23.40, -, -, 25.37
00:03:14, 22.75, 23.14, -, -, 25.31
00:03:15, 22.75, 23.34, -, -, 25.31
```

Each time the user hits the logging start/stop button the time should reset to zero for the CSV. Because the CSV file and serial terminal should always have the same output string (https://github.com/PaxInstruments/t400-firmware/issues/32), the terminal should also reset time to zero.

The serial output should look like this:
```
00:03:07, 22.75, 22.95, -, -, 25.31
00:03:08, 22.75, 23.14, -, -, 25.51
00:03:09, 22.75, 23.14, -, -, 25.51
Logging to:
LD0029.CSV
00:00:00, 22.69, 23.08, -, -, 25.25
00:00:01, 22.75, 23.14, -, -, 25.31
00:00:02, 22.81, 23.40, -, -, 25.37
00:00:03, 22.75, 23.14, -, -, 25.31
00:00:04, 22.75, 23.34, -, -, 25.31
```

If we pop the header into the serial terminal too (https://github.com/PaxInstruments/t400-firmware/issues/154), it would look like this
```
00:03:07, 22.75, 22.95, -, -, 25.31
00:03:08, 22.75, 23.14, -, -, 25.51
00:03:09, 22.75, 23.14, -, -, 25.51
Logging to:
LD0029.CSV
time, ambient, sens0, sens1, sens2, sens3
00:00:00, 22.69, 23.08, -, -, 25.25
00:00:01, 22.75, 23.14, -, -, 25.31
00:00:02, 22.81, 23.40, -, -, 25.37
00:00:03, 22.75, 23.14, -, -, 25.31
00:00:04, 22.75, 23.34, -, -, 25.31
```

**Comment by cibomahto** [comment]
this should probably be 

Logging to: LD0029.CSV
time, ambient, sens0, sens1, sens2, sens3
000000, 22.69, 23.08, -, -, 25.25
000001, 22.75, 23.14, -, -, 25.31
000002, 22.81, 23.40, -, -, 25.37
000003, 22.75, 23.14, -, -, 25.31
000004, 22.75, 23.34, -, -, 25.31

Splitting elapsed time into hms adds a lot of computation both in generating the report and doing something with the data afterward.

**Comment by cibomahto** [comment]
Actually the label should include the unit:

time(s), ambient(°C), sens0(°C), sens1(°C), sens2(°C), sens3(°C)

and similar

**Comment by charlespax** [comment]
Okay, cool. Then let's drop the hh:mm:ss and just do seconds. How about dropping the leading zeros?

**Comment by charlespax** [comment]
I agree with the addition of the units. Should we drop the degree symbol though? It's an extended ASCII character. Would that potentially cause problems?

**Comment by cibomahto** [comment]
Implemented in . There is space for 99999999 s, or something like 3 years.

Logging to:
LD0022.CSV
time (s), ambient (C), sens0 (C), sens1 (C), sens2 (C), sens3 (C)
       1, 29.94, 28.94, -, 28.94, -
       2, 29.88, 28.88, -, 27.88, -
       3, 29.94, 28.94, -, 27.94, -
       4, 29.94, 28.94, -, 28.94, -
       5, 29.94, 28.94, -, 28.94, -
       6, 29.94, 28.94, -, 28.94, -
       7, 29.94, 28.94, -, 28.94, -
       8, 29.94, 28.94, -, 28.94, -
       9, 29.94, 28.94, -, 28.94, -
      10, 29.94, 28.94, -, 28.94, -
