### ISSUE TITLE
Serial: Print clock time to serial port

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#39]

**Comment by cibomahto** [comment]
Clock is being printed at every measurement, is there something else it should be doing?
![screen shot 2015-02-19 at 10 52 38 pm](https://cloud.githubusercontent.com/assets/44493/6268763/210738d0-b88a-11e4-9aff-7c4c7a3b27cd.png)

**Comment by charlespax** [comment]
I like the way you have it now where on each line you give hh:mm:ss since logging began. Would we gain anything significant by doing something else? Maybe it would be good to make it dd:hh:mm:ss.

We could have the date and time in the header if each file and from there just list the seconds with each reading. I don't thing that would gain us much.

We could list the date, time, and log interval in the header and from there the time of each reading can be calculated. The user would have extra work to do when plotting readings in any program.

In addition to having the stopwatch time on each line we can have click time on each line. Then we could corelate readings between devices. However, this would require the user be able to configure the date and time, which is not in the plan right now.

**Comment by cibomahto** [comment]
Ok, closing this since it doesn't represent a concrete issue. If there is a specific functionality from the above ideas that should be implemented, please open a new issue.

**Comment by charlespax** [comment]
We are not implementing the ability for the user to configure the RTC date/time (https://github.com/PaxInstruments/t400-firmware/issues/153), so the clock time the RTC gives is not meaningful.

However, this may be something we do in the future. I'm reopening the issue and moving it to the ices box along with issue #153.

If we do implement this we should have a column for the actual date/time and another column for the time since logging began. This would avoid the user having to configure their time axis when graphing in a program.

Output of the serial terminal:
```
00:03:07, 22.75, 22.95, -, -, 25.31
00:03:08, 22.75, 23.14, -, -, 25.51
00:03:09, 22.75, 23.14, -, -, 25.51
Logging to:
LD0029.CSV
00:03:11, 22.69, 23.08, -, -, 25.25
00:03:12, 22.75, 23.14, -, -, 25.31
00:03:13, 22.81, 23.40, -, -, 25.37
00:03:14, 22.75, 23.14, -, -, 25.31
00:03:15, 22.75, 23.34, -, -, 25.31
00:03:16, 22.75, 23.14, -, -, 25.31
00:03:17, 22.75, 23.14, -, -, 25.11
00:03:18, 22.75, 23.14, -, -, 25.11
00:03:19, 22.75, 23.14, -, -, 25.11
00:03:20, 22.75, 23.14, -, -, 25.11
00:03:21, 22.75, 23.14, -, -, 25.11
```

Output of the CSV file:
```
time, ambient, sens0, sens1, sens2, sens3
00:03:11, 22.69, 23.08, -, -, 25.25
00:03:12, 22.75, 23.14, -, -, 25.31
00:03:13, 22.81, 23.40, -, -, 25.37
00:03:14, 22.75, 23.14, -, -, 25.31
00:03:15, 22.75, 23.34, -, -, 25.31
00:03:16, 22.75, 23.14, -, -, 25.31
00:03:17, 22.75, 23.14, -, -, 25.11
00:03:18, 22.75, 23.14, -, -, 25.11
00:03:19, 22.75, 23.14, -, -, 25.11
00:03:20, 22.75, 23.14, -, -, 25.11
00:03:21, 22.75, 23.14, -, -, 25.11
```

**Comment by charlespax** [comment]
Will not implement. Closing issue.
