### ISSUE TITLE
Buttons: Button cycles graph display

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#44]
1, 2, 3, 4, (1, 2, 3, 4)

**Comment by cibomahto** [comment]
What happens if the selected channel isn't connected?

**Comment by charlespax** [comment]
The interface should still cycle through all four channels. If there is not data to display, then the graph would be empty. If there is data in the buffer from when the TC was connected, the graph could show that.

**Comment by charlespax** [comment]
Woops! I meant to have this in Milestone 4. This is the whole purpose of the graph button in the upper left.
