### ISSUE TITLE
Scale vertical graph axis based on data range

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#62]
Ensure the graph's vertical axis can display the temperature range. Maybe truncate some of the data points to move the axis to the right at high temperatures. Maybe use a smaller font, but that takes up more memory.

**Comment by charlespax** [comment]
Let's agree on a concrete implementation for this.

When the temperature is 90 temperature units and -5 temperature units we only need two characters to the left of the graph to properly label the graph.
![screenshot-onetc-big](https://cloud.githubusercontent.com/assets/281642/6039290/795f7038-aca0-11e4-8cba-10179befea28.png)

For temperatures at or above 100 units or at or below -10 units, we need three characters to properly label the graph.
![screenshot-onetc-boiling-big](https://cloud.githubusercontent.com/assets/281642/6039291/79f7f772-aca0-11e4-8c58-9b685c8ab546.png)

For temperatures at or above 1000 units or at or below -100 units, we need four characters to properly label the graph. I have no screen shot, but you can imagine how it would look.

What are the possible values?
Absolute zero = –273.15 C, = -459.67 F = 0 K

**Comment by cibomahto** [comment]
Implemented in 47295a5. Should work from ~ -999 to 9000, outside of that the graph draws incorrectly.
