### ISSUE TITLE
Disable buttons while logging

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#79]
It could be good to disable some buttons while the device is logging to SD card. Just a thought.
- Time interval. Each .csv files should have a single time interval, which is printed at the top of the file
- Power

Maybe it's fine to have more than one time interval in a .csv files. The deltaT appears on each line, so there isn't a strong technical argument for disabling this button.

The start/stop button stops logging with a touch, so what's the problem if PWR does the same?

**Comment by charlespax** [comment]
Moving to UX.

**Comment by cibomahto** [comment]
Implemented in fed283e1. Power button, unit toggle (not implemented), log interval buttons disabled when logging. Backlight, channel display (not implemented), and start/stop log are still active.
