### ISSUE TITLE
Support FAT32

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#82]
Can the T400 support FAT32 filesystems. The library right now can only support FAT16. Maybe operate FAT32 cards in FAT16 mode?

See #34 #74 #75 for background.

**Comment by charlespax** [comment]
It looks like we may be able to support FAT32 if we drip Arduino compatibility. FAT32 is waaay more important than Arduino compatibility. Let's do it if we can.

**Comment by cibomahto** [comment]
I'm estimating this will probably take 15+ hours to complete. I suggest moving this to a future release.

**Comment by charlespax** [comment]
Darn!, that would have been awesome.

Is that fifteen hours because we would have to write a new library from scratch? Do we shorten that time if we free up memory by moving string and things to the SPI flash (https://github.com/PaxInstruments/t400-firmware/issues/101)?

**Comment by cibomahto** [comment]
It's accounting for the effort that it will take to port the main code and libraries out of Arduino. Possible, but probably not the best use of effort at this time.

**Comment by cibomahto** [comment]
So check this out- Arduino's SD library is way too big to fit, but by using the underlying library directly (SdFat, from: https://github.com/greiman/SdFat), Fat32 seems to fit no problem. Implemented in d1774e4. There's still some error checking that needs to be in, but it works with a card formatted for 8gb using os x disk utility.

With this included we're at:
Sketch uses 26,728 bytes (93%) of program storage space. Maximum is 28,672 bytes.
Global variables use 1,891 bytes (73%) of dynamic memory, leaving 669 bytes for local variables. Maximum is 2,560 bytes

**Comment by charlespax** [comment]
OMFG!!! This is flipping awesome! I'm going to play with it right now...

Tested and working on a 1 GB microSD card formatted in OSX as FAT32. I'll have to find high capacity cards to test.

**Comment by charlespax** [comment]
I had Pax Instruments for the SdFat library, so we can direct users to a know code base. I've updated the URL in README.md and in t400.ino.

See https://github.com/PaxInstruments/SdFat
