### ISSUE TITLE
Sleep CPU between readings

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#84]
Put the CPU into low power sleep between readings. Wake up via RTC interrupt, see #53. This should happen in a low power specific mode. Maybe a button needs to be held down for some time. The LCD would not update, only sleep, read, log. Maybe an LED on board would be good to indicate the thing still works.

**Comment by cibomahto** [comment]
Sleep between readings is implemented now. Not updating the display while logging seems a little dubious- the display only updates when a measurement is taken, and it's low power anyway, so why not update it? Anyway, your call.

**Comment by charlespax** [comment]
Let's keep updating the display. Otherwise, it will be super confusing. If a user needs super long battery life for logging, they can plug into an adapter. Closing issue.
