### ISSUE TITLE
Pair down u8glib font

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#94]
Change the u8glib font to only the characters used on the device. This is a great reason to use the dashes to indicate thermocouple disconnection rather than "NoTC". https://github.com/PaxInstruments/t400-firmware/issues/77

Ref, "Between the u8glib, vprintf, sd and usb there is not much left of the 32K flash.  Having an open source project with low memory margin is not great but on the other hand the Arduino compatibility is a big plus IMO. Some u8glib fonts require more memory than others, and possibly you make the existing fonts sparse, including only characters that you need (yak). There are other memory considerations with u8glib, for example drawing a rounded rectangle pulls the circle logic which adds ~800B IIRC.  If you need to speed up the drawing there are also tricks for that (you don't need to redraw the entire screen on each iteration of the picture loop, just that portion of the screen. BTW, the u8glib developer is very responsive on the Android/Display forum." -zapta http://www.eevblog.com/forum/oshw/pax-instruments-t400-thermocouple-temperature-datalogger/

**Comment by charlespax** [comment]
Files that were needed: u8glib files needed: u8g_clip.c, u8g_com_api.c, u8g_com_arduino_common.c, u8g_com_arduino_sw_spi.c, u8g_delay.c, u8g_dev_st7565_lm6063.c, u8g_font_data.c, u8g_font.c, u8g_line.c, u8g_ll_api.c, u8g_page.c, u8g_pb.c, u8g_pb8v1.c, u8g_rot.c, u8g_state.c, u8g.h, U8glib.cpp, U8glib.h. See https://github.com/PaxInstruments/t400-firmware/issues/121

**Comment by cibomahto** [comment]
Removing the unused files shouldn't change anything. Use an ELF inspection program to look at what's actually being included in the firmware-

In Arduino preferences, enable verbose output during compilation to get the location of the .elf file
Then use avr-readelf to look at everything included in the binary, including the size:
avr-readelf /var/folders/4x/1098rs3s6n3g6vqgl89p5msr0000gn/T/build2511438885760059927.tmp/t400.cpp.elf -a

Finally, filter out just the u8g* portions, and count their size (i imported it into libreoffice but there's probably a more straightforward way).

**Comment by cibomahto** [comment]
Long story short, I swapped in a font that doesn't have extended characters (u8g_font_5x8r), and it dropped by ~700b. I don't think this will go much further without abandoning u8glib, so maybe close this for now.
