### ISSUE TITLE
Consider switching to a different graphic library

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#96]
Maybe u8glib is too beefy because it supports so many displays. Maybe it can be optimized of there exists a more appropriate library.

Ref, "Between the u8glib, vprintf, sd and usb there is not much left of the 32K flash. Having an open source project with low memory margin is not great but on the other hand the Arduino compatibility is a big plus IMO. Some u8glib fonts require more memory than others, and possibly you make the existing fonts sparse, including only characters that you need (yak). There are other memory considerations with u8glib, for example drawing a rounded rectangle pulls the circle logic which adds ~800B IIRC. If you need to speed up the drawing there are also tricks for that (you don't need to redraw the entire screen on each iteration of the picture loop, just that portion of the screen. BTW, the u8glib developer is very responsive on the Android/Display forum." -zapta http://www.eevblog.com/forum/oshw/pax-instruments-t400-thermocouple-temperature-datalogger/

**Comment by cibomahto** [comment]
Looking at the output file, the obvious parts of u8glib take a little over 5k (including the font). I'm pushing this to icebox for now, since it's not blocking anything at the moment.

**Comment by charlespax** [comment]
If we run into a memory limit this will be an obvious thing to look into. Closing issue.
