### ISSUE TITLE
Sample rate changes not reflected in the graph

### ISSUE THREAD

**Issue by cibomahto** [PaxInstruments/t400-firmware#98]
When the user changes the sample rate, the previous data points are shown on the graph at the same x scale as the previous points. This could cause the data to be misinterpreted, if the user isn't paying attention.

**Comment by charlespax** [comment]
When we compress for time we can either wipe the data or save it incase the user changes the sample rate again. Let's just wipe the data. If the user is not logging, it's transient data.

**Comment by cibomahto** [comment]
Done in 3f70144
