### ISSUE TITLE
Expand Y-axis temperature labels

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#99]
The graph currently display the most recent one-hundred readings when there are only two digits displayed on the graph Y-axis. When the graph scales we need to display larger digits as the temperature goes to 100 C and above or -10 C and below. We can truncate the graph to only show 90 readings. That will give us ten extra pixels, which is two digits.

**Comment by cibomahto** [comment]
Working as of tonight with test data, from 2-4 characters. The effects of this will be noticeable when #62 is closed.
